### ISSUE TITLE
Overview of failed Services and/or their Elements

### ISSUE THREAD

**Issue by SigritSiht** [buerokratt/Service-Module#10]
AS A Service Manager
I WANT TO have an overview of failed Services and/or their Elements
SO THAT I could enforce the technical team to get them fixed

> https://www.figma.com/file/yF3ywx7OaufCTXlQNpJ1ub/B%C3%BCrokratt-Service-module-2023.03?node-id=286-32213

> Logs deep-dive is done by using appropriate (DevOps and/or Service Managers) tools
> The Analytics Module also covers finding buggy Services (among others)

> The scope of this issue is to give a near real-time overview of Services / Elements that are _currently_ not working in `test` and `production`

### Acceptance Criteria

- [ ] Group by Services / Elements / both
- [ ] Faulty Services with their details are shown in a pop-up in a human-readable format
- [ ] Only the Services / Elements that are _currently_ not working are shown
- [ ] If all the Services are working correctly, this sub-page is empty
- [ ] No historical view of previously failed Services / Elements is shown on this sub-page
- [ ] All of the above applies to both `test` and `production` environments

#### GUI

- [ ] Use existing filtering components to filter values by column
- [ ] Environment where the problem occurs, is clearly stated in a separate filterable column
- [ ] REST endpoint `/overview/services-detailed/nok` is used to fetch a list of faults

#### ETL pipelines

> ETL pipelines are out of the scope of this issue and will be done internally by Bürokratt

- [ ] Ruuter logs are transported to an appropriate OpenSearch index

#### DSL

- [ ] REST endpoint `/overview/services/nok` to fetch a list of currently faulty Services
- [ ] REST endpoint `/overview/elements/nok` to fetch a list of currently faulty Elements

The above endpoints will be used and merged by
- [ ] REST endpoint `/overview/services-detailed/nok` to fetch a list of currently faulty Services with details about the Elements causing the problems, covering `Elements` and `count` for the total times the error has occurred
- [ ] #91 is used as input for the endpoints above

##### Opensearch

- [ ] Index schema
- [ ] REST endpoints to populate index schema with mock data for initial testing
- [ ] Fetch data based on a specific Ruuter request ID
- [ ] Fetch data based on business-level AC requirements

**Comment by turnerrainer** [comment]
@SigritSiht we have developments planned for that done within another procurement ([CentOps](https://github.com/orgs/buerokratt/projects/23/views/1)).

But this issue still makes sense as these are Service Module-specific requirements. Links to GUI to guide to proper CentOps dashboards should be created.

**Comment by turnerrainer** [comment]
>@SigritSiht 
>...
>- [ ] log files' export to file created
>- [ ] log files' export files can be downloaded

1. These ACs will be defined by CentOps;
2. Most likely, CentOps will set restrictions to exporting logs to prevent potential security risks (in production).

**Comment by SigritSiht** [comment]
Previously mentioned AC's deleted because they were not important and didn't add much to the project.

**Comment by baha-a** [comment]
> Most of the functionality should belong to the Analytics Module

> Should be part of the Analytics Module

Hi @turnerrainer, What exactly do these mean? Does it imply that the code for this issue should be included within the Analytics Module repository? Or is it sufficient for the related page to only appear under the Analytics Module section in the user interface?

**Comment by turnerrainer** [comment]
This task for previously called _"Service's feedback based on Ruuter logs"_

**Comment by trevorling** [comment]
@turnerrainer 
[Figma link](https://www.figma.com/file/yF3ywx7OaufCTXlQNpJ1ub/B%C3%BCrokratt-Service-module-2023.03?node-id=286%3A32213&t=KOJW0b4q8rVUBK06-1)

**Comment by 1AhmedYasser** [comment]
@turnerrainer Blocked Waiting Ruuter Changes on error handling

**Comment by ValterAro** [comment]
This issue can not be fully tested until the services have been fully integrated in the Bürokratt and you can try the services through the chatbot.

**Comment by matKlju** [comment]
Current issue will need more Grooming and a general update as a lot  changes have been deployed since last log.
