### ISSUE TITLE
Service Module landing page

### ISSUE THREAD

**Issue by SigritSiht** [buerokratt/Service-Module#11]
AS an Administrative User
I WANT TO have a separate sub-module of admin portal
SO THAT I CAN start creating a new service and/or view and edit existing services

### Acceptance Criteria

- [x] button  "Loo uus teenus" ("Create new service") created (directs to Training Module Intents view)
- [ ] "message board" for system notes created (messages to be printed out to Bürokratt user like "New services have been created, **train model**" _-- the latter refers to an appropriate Training Module's link_)
- [x] table containing "Olemasolevad teenused" (Existing services) created
- [ ] table columns: Teenuse nimi (Service name); Teenuse kasutamise arv (Times Service has been triggered); Muuda teenust (Edit Service), takes to #12 ; Teenuse olek (Activate/Deactivate Service) [action]; Kustuta teenus (Delete Service) [action] created, takes to #14 
- [x] conformation pop-up with information about deletion process (i.e. data will be deleted etc) created and triggered when Delete service button is pressed
- [x] when changing the status of a Service, a modal to confirm or discard the selection (with appropriate information) appears

#### GUI

- [x] All input as configurable `i18n` values

#### DSL

- [x] #38
- [x] #39
- [ ] Delete an inactive Service by using #14 and following #24
- [ ] #41

**Comment by SigritSiht** [comment]
![Image](https://user-images.githubusercontent.com/25658198/192512026-4bd83905-7642-4cef-83c1-0e1f8b9f7574.png)

**Comment by SigritSiht** [comment]
@Minwasko discussed with UX. 4.AC should be changed to Muuda - > directs to intent in Training Module.

**Comment by 1AhmedYasser** [comment]
@allarlaaneleht @turnerrainer  i contacted the developer who worked on it and he mentioned the following 
```
We never got the final decision on what it should actually do. It was supposed to point somewhere inside training module, as theoretically 1st step for creating a service starts there, but we didn’t fully connect them, so never got the final answer on what to do with it and we agreed that it would stay as is for now
```
What is your plan with it at the moment

**Comment by allarlaaneleht** [comment]
BUG: The link "Treeni uus mudel" directs to localhost URL.
![treeniuusmudellink](https://github.com/buerokratt/Service-Module/assets/139747282/6f8d3edd-14bd-4506-a60f-3219f95c1332)

![image](https://github.com/buerokratt/Service-Module/assets/139747282/f354a2fc-5145-4d49-8426-ded6f03f31fc)

**Comment by allarlaaneleht** [comment]
> @allarlaaneleht @turnerrainer i contacted the developer who worked on it and he mentioned the following
> 
> `We never got the final decision on what it should actually do. It was supposed to point somewhere inside training module, as theoretically 1st step for creating a service starts there, but we didn’t fully connect them, so never got the final answer on what to do with it and we agreed that it would stay as is for now`
> 
> What is your plan with it at the moment

@1AhmedYasser Change button should direct you to the service module connection page in order to change an already existing service.

**Comment by turnerrainer** [comment]
https://github.com/buerokratt/Service-Module/issues/142 should be used to create this new funcitonality. Not a bug.

**Comment by 1AhmedYasser** [comment]
> 3\. http://localhost:3001/treening/treeni-uus-mudel

@varmoh
This link should be configured on the environment to point to training module in docker compose here 

```
gui_dev:
    container_name: gui_dev
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8085
      - REACT_APP_TRAINING_MODULE_GUI_BASE_URL=http://localhost:3001
      - PORT=3006
    build:
      context: ./GUI
      dockerfile: Dockerfile.dev
    ports:
      - 3006:3006
    volumes:
      - /app/node_modules
      - ./GUI:/app
    networks:
      - bykstack
```

**Comment by ValterAro** [comment]
BUG:
Short summary: Changed the Local storage i18nextLng key value to "en", but the menu is in Estonian although the selected language is English
Expected result: The menu should be in English
Real result: The menu is still in Estonian
How to reproduce the bug:  Go to https://admin.dev.buerokratt.ee/services/overview after loging in through test tara and change the i18nextLng value to en from et. After this refresh the page.
Pic or video: see below
Note: Let me know if this should be tested some other way. Additionally, when adding a service and pressing live endpoint tab, then the tab next to it says "+ Lisa testkeskkond" in Estonian. This should also be in English

![Image](https://github.com/buerokratt/Service-Module/assets/122787093/d2aca38b-1c0b-46bc-8ea4-55ad4caf6119)

**Comment by ValterAro** [comment]
BUG:
Short summary: When adding a new service and during the 2nd step (Service setup). You should also see the possibility to add a header/body or a parameter before making a successful request. Currently in some cases I need to manually add the parameter to the url and then remove it.
Expected result: When adding a Custom endpoint, then below API endpoint URL there is also the option to add params, headers and body,
Real result: Currently you first need a successful test of the URL and then it enables the option to add params, headers and body
How to reproduce the bug: Go to https://admin.dev.buerokratt.ee/services/newService and add a new live endpoint, select Custom endpoint and then you only see the option to enter the URL. For example I need to enter https://petstore3.swagger.io/api/v3//pet/findByStatus?status=available for it to go through and then remove the status part and add it as a variable in the params.
Pic or video: see below


![Image](https://github.com/buerokratt/Service-Module/assets/122787093/931f5c6c-f05f-4b35-8b70-67df2389e5bf)

**Comment by ValterAro** [comment]
[BUG]
Short summary: In the service module overview when changing the state of the service in the list, then the popup message says that it failed, but after refreshing the page it shows that the state has changed (for example from active to deactivated). There is similar problem with "kustuta" / "delete" that the popup says it fails, but it actually seems to work.
Excpected result: When presssing the delete button or changing the state of the service in the list it says that the request was successful
Real result: When changing the state of the service, the popup says the action failed.
How to reproduce: After logging in, go to https://admin.dev.buerokratt.ee/services/overview and change the state or delete one of the items in the services list. You will see a popup that says it failed, but after refresh the action is done.
Pic:


![Image](https://github.com/buerokratt/Service-Module/assets/122787093/a2450926-0a9a-471f-9eff-c2107ab45ea3)

**Comment by ValterAro** [comment]
[BUG]
Short summary: In the service module overview page, when using the hyperlink for "Treeni uus mudel" / "Train a new model" then the user is redirected to the page: "http://localhost:3001/treening/treeni-uus-mudel" instead of "https://admin.dev.buerokratt.ee/training/train-new-model"
Expected result: user is directed to "https://admin.dev.buerokratt.ee/training/train-new-model"
Real result: user is directed to "http://localhost:3001/treening/treeni-uus-mudel" 
How to reproduce: After logging in, go to https://admin.dev.buerokratt.ee/services/overview and below the table there is some text with the hyperlink at the end with the text "Treeni uus mudel". After clicking it the user is sent on the wrong url.

**Comment by 1AhmedYasser** [comment]
> BUG: Short summary: Changed the Local storage i18nextLng key value to "en", but the menu is in Estonian although the selected language is English Expected result: The menu should be in English Real result: The menu is still in Estonian How to reproduce the bug: Go to https://admin.dev.buerokratt.ee/services/overview after loging in through test tara and change the i18nextLng value to en from et. After this refresh the page. Pic or video: see below Note: Let me know if this should be tested some other way. Additionally, when adding a service and pressing live endpoint tab, then the tab next to it says "+ Lisa testkeskkond" in Estonian. This should also be in English
> 
> ![Image](https://user-images.githubusercontent.com/122787093/281371704-d2aca38b-1c0b-46bc-8ea4-55ad4caf6119.png)

Regarding the menu part here, @ExiRain is the header & menu taking their language from the browser i18nextLng because i found the language hardcoded as et in `renderMenuTree`, could you please check it

**Comment by turnerrainer** [comment]
@ExiledRain has solved it. @ExiledRain , please link the appropriate PR here.

**Comment by 1AhmedYasser** [comment]
> ATR until "It will be solved when the service connection to intent is completed" (By Ahmed).

Then please move it to blocked not at rejected and i will check it again once its added

**Comment by ValterAro** [comment]
Short summary: The next page button and the "Kuvan korraga(results per page)" does not work. Meaning that currently you can not see the services beyond the first page and the first 10 results.

**Comment by ValterAro** [comment]
Currently seems to work as intended. Later need to test whether "times service has been used" shows the correct number once services can be trained for use.

**Comment by ValterAro** [comment]
This bug is still present in the dev environment https://github.com/buerokratt/Service-Module/issues/11#issuecomment-1838554487 .

**Comment by 1AhmedYasser** [comment]
> The bug "Short summary: The next page button and the "Kuvan korraga(results per page)" does not work. Meaning that currently you can not see the services beyond the first page and the first 10 results." is fixed and waiting for the service connection to intent to be implemented for the final fix.


https://github.com/buerokratt/Service-Module/assets/26207361/00c2e75e-9173-4088-84b2-47fb0a41b5d2

@ValterAro i checked this on dev and it seems working fine, am i missing something here ?

**Comment by 1AhmedYasser** [comment]
> [BUG] Short summary: In the service module overview when changing the state of the service in the list to inactive from active state, then the popup message says that it failed, but after refreshing the page it shows that the state has changed. There is similar problem with "kustuta" / "delete" that the popup says it fails, but it actually seems to work. Excpected result: When presssing the delete button or changing the state of the service in the list it says that the request was successful Real result: When changing the state of the service, the popup says the action failed. How to reproduce: After logging in, go to https://admin.dev.buerokratt.ee/services/overview and change the state to inactive or delete one of the items in the services list. You will see a popup that says it failed, but after refresh the action is done.

Fixed Here https://github.com/buerokratt/Service-Module/pull/199

For now, will modify the file location and database field, but it will be further modified when working on https://github.com/buerokratt/Service-Module/issues/196

**Comment by ValterAro** [comment]
Seems to work as intended.
