### ISSUE TITLE
Service Module Connection Page

### ISSUE THREAD

**Issue by SigritSiht** [buerokratt/Service-Module#12]
AS an Administrative User
I WANT TO have a dedicated sub-page of admin portal "Tagatuba" for defining service endpoints and/or SQL queries
SO THAT I CAN enter needed information about query/queries that must be performed to provide Service to end-user

> This issue is to define the endpoints, sticky Services, etc. that will be used for the final setup at https://github.com/buerokratt/Service-Module/issues/20

### Acceptance Criteria

> ["Loo uus teenus" in Figma](https://www.figma.com/file/yF3ywx7OaufCTXlQNpJ1ub/B%C3%BCrokratt-Service-module-2023.03?node-id=15-23280)

- [x] New services can be created based on API endpoints
- [ ] New services can be created based on [X-Road services](https://x-tee.ee/catalogue/EE)
- [x] New services can be created based on database queries
- [x] When adding new endpoints, their response is automatically validated by
- [ ] #37
...
- [x] text field for entering Service name created
- [x] text field for entering Service description created
- [x] text field for entering URL (API endpoint or link to X-Road service catalogue) created
- [x] Text field for necessary API auth values created
- [x] button to add more request URLs created
- [x] button "Get request body" created (#9 )
- [ ] text fields for entering request variables (query input(s)) created (only visible if providing of request body automatically fails)
- [ ] #36
- [ ] Custom Endpoints Url Field Contains Smart Url Parsing to detect parameters and automatically add them

#### GUI

- [ ] Related to #45

**Reguest's key value of "Teenuse seadistamine" / "Service settings"**

- [ ] In case of `Client's Input`, the variable used will be `{{ClientInput.N}}`, for example `{{ClientInput.1}}`, `{{ClientInput.2}}`, `{{ClientInput.3}}`, etc. (only incremental numbers)
- [ ] In case of `TARA authentication`, response output schemas are pre-defined and used for example `{{TARA.personcalCode}}`, etc., schemas received via REST call -- see #103 
- [ ] When defining a service via 3 steps, jumping back and forth over the 2nd and 3rd steps is allowed -- no validations are made until the Service is tested and/or saved
- [ ] Requests can be multi-stepped - [see Figma example](https://www.figma.com/file/yF3ywx7OaufCTXlQNpJ1ub/B%C3%BCrokratt-Service-module-2023.03?node-id=498-31967&t=NUpW61jkWD3orTox-4)

#### DSL

- [ ] Uses #9 as input
- [ ] #34
- [ ] #35

**Comment by SigritSiht** [comment]
![Image](https://user-images.githubusercontent.com/25658198/196414093-13e2f364-edd1-4451-9a31-cb2b75aa5a7e.png)

**Comment by turnerrainer** [comment]
> samas kas üldse kunagi tahame lubada miskit muud kui GET?

@SigritSiht definitely.

**Comment by turnerrainer** [comment]
@SigritSiht would it make sense to create, etc services via Drag & Drop GUI (https://github.com/orgs/buerokratt/projects/16)? In the end, it's just another YAML manipulation.

**Comment by SigritSiht** [comment]
@turnerrainer just a reminder why this issue is no longer To Groom and instead back to To Do.
I have added only one additional AC for the Resql component as per previous discussions.
Please either confirm that it is OK and enough for what we are trying to do (i.e enable SQL queries) or create more ACs or tasks that are in your opinion missing.

**Comment by SigritSiht** [comment]
@turnerrainer we should probably ask both LIVE and TEST URLs/DB. To make sure we can test the flow using TEST and to provide service use LIVE.

i.e yo uhave to enter both https://avaandmed.eesti.ee/api/datasets and https://avaandmedtest.eesti.ee/api/datasets

**Comment by SigritSiht** [comment]
Blocked because of UX.

**Comment by SigritSiht** [comment]
First look of UX is kind of done, but still in Progress for a few days at least.

**Comment by SigritSiht** [comment]
Automatic save trigger is missing as an AC, needed so user's done work would remain as Draft.

**Comment by trevorling** [comment]
[Figma Link](https://www.figma.com/file/yF3ywx7OaufCTXlQNpJ1ub/B%C3%BCrokratt-Service-module-2023.03?node-id=15%3A23280&t=YR8fHz3hqfaHjaAi-1)

**Comment by allarlaaneleht** [comment]
BUG: Under Service setup, if Open API endpoint is chosen, you should only be able to fill in the Endpoint name and API endpoint URL before asking for endpoints. However, if you change to custom endpoint and then change back to Open API endpoint, other fields appear which they should not do.
Video: https://drive.google.com/file/d/1kfiBGYzvIgOQzpeehK1Gborkbd6KilRC/view?usp=sharing

**Comment by allarlaaneleht** [comment]
@varmoh Please deploy the updates.

**Comment by allarlaaneleht** [comment]
1. Short summary: When choosing the value of the API endpoint, the drop-down menu of values to choose from does not appear. The menu appears only when a character is typed to the box. 
2. Expected result: When choosing the value of the API endpoint, the drop-down menu of values to choose from should appear, so you could choose from different values. 
3. Real result: The menu appears only when a character is typed to the box.
4. How to reproduce the bug: Fill in the endpoint boxes, click on the values box.
5. Video: https://drive.google.com/file/d/1ZcAUXMQfie37SWzAgsT8HCzhdX2qjfpc/view?usp=sharing

**Comment by ValterAro** [comment]
BUG:
Short summary: When adding a new service and during the 2nd step (Service setup). You should also see the possibility to add a header/body or a parameter before making a successful request. Currently in some cases I need to manually add the parameter to the url and then remove it.
Expected result: When adding a Custom endpoint, then below API endpoint URL there is also the option to add params, headers and body,
Real result: Currently you first need a successful test of the URL and then it enables the option to add params, headers and body
How to reproduce the bug: Go to https://admin.dev.buerokratt.ee/services/newService and add a new live endpoint, select Custom endpoint and then you only see the option to enter the URL. For example I need to enter https://petstore3.swagger.io/api/v3//pet/findByStatus?status=available for it to go through and then remove the status part and add it as a variable in the params.
Pic or video: see below


![Image](https://github.com/buerokratt/Service-Module/assets/122787093/931f5c6c-f05f-4b35-8b70-67df2389e5bf)

**Comment by ValterAro** [comment]
[BUG]
Short summary: When adding a new service and during the 2nd step (Service setup). When using a url that needs additional parameters, then they should be added automatically to the request, when the parameters are added at the params part. For some reason the blue text is also not visible anymore as seen in the picture.
Expected result: I expect the request in the picture to be successful
Real result: the request fails
How to reproduce: Go to https://admin.dev.buerokratt.ee/services/newService and add a new live endpoint, select Custom endpoint and then you only see the option to enter the URL. For example I need to enter https://petstore3.swagger.io/api/v3//pet/findByStatus and then add a parameter "status" with the value "available"
Pic:


![Image](https://github.com/buerokratt/Service-Module/assets/122787093/a43a3623-0c35-42bf-a331-bca65f60163a)

**Comment by 1AhmedYasser** [comment]
> [BUG] Short summary: When adding a new service and during the 2nd step (Service setup). When using a url that needs additional parameters, then they should be added automatically to the request, when the parameters are added at the params part. For some reason the blue text is also not visible anymore as seen in the picture. Expected result: I expect the request in the picture to be successful Real result: the request fails How to reproduce: Go to https://admin.dev.buerokratt.ee/services/newService and add a new live endpoint, select Custom endpoint and then you only see the option to enter the URL. For example I need to enter https://petstore3.swagger.io/api/v3//pet/findByStatus and then add a parameter "status" with the value "available" Pic:
> 
> ![Image](https://user-images.githubusercontent.com/122787093/283741144-a43a3623-0c35-42bf-a331-bca65f60163a.png)

The Current Implementation of custom endpoint is that you have to enter everything manually, as for OpenAPI endpoint you enter the url and everything is fetched automatically.

**Url smart parsing is not available in the scope at the moment**
```
smart pasing: https://petstore3.swagger.io/api/v3/pet/findByStatus?status=available
Url = https://petstore3.swagger.io/api/v3/pet/findByStatus
Parameters: status: available
```
As for the button css bug its fixed here: https://github.com/buerokratt/Service-Module/pull/160

**Comment by turnerrainer** [comment]
Needs additional grooming based on @1AhmedYasser comment.

**Comment by 1AhmedYasser** [comment]
> Needs additional grooming based on @1AhmedYasser comment.

- [ ] Custom Endpoints Url Field Contains `Smart Url Parsing` to detect parameters and automatically add them

**Comment by ValterAro** [comment]
Waiting for the XTR module to work.

**Comment by 1AhmedYasser** [comment]
> Waiting for the XTR module to work.

Then move it to blocked if its waiting some developments in other places

**Comment by ValterAro** [comment]
Feature request: When adding a endpoint and using OpenAPI spec, then the current implementation does not take into account the list of possible values for a variable, even though they are in the documentation. It would be great to have the acceptable values be available for the user.
For example: in the https://petstore3.swagger.io/api/v3/openapi.json there is enum for the possible status values:
"parameters": [
{
  "name": "status",
  "in": "query",
  "description": "Status values that need to be considered for filter",
  "required": false,
  "explode": true,
  "schema": {
    "type": "string",
    "default": "available",
    "enum": [
      "available",
      "pending",
      "sold"
]
}
}
],

**Comment by 1AhmedYasser** [comment]
Blocked waiting for https://github.com/buerokratt/XTR/issues/4

**Comment by matKlju** [comment]
Wont do. The task will be used a reference.
