### ISSUE TITLE
Test Service Flow

### ISSUE THREAD

**Issue by SigritSiht** [buerokratt/Service-Module#16]
AS AN Administrative user
I WANT TO test the compoments of the service flow on #20
SO THAT I CAN make sure that the service flow is complete and logical.

> ~See https://xd.adobe.com/view/cb1ca0df-2dea-4432-a05d-bb75db6e2e5f-9e4f/screen/fff5de82-8d66-4563-ae2e-a49214039214 view nr 3 as an example of what to test~

> https://www.figma.com/file/yF3ywx7OaufCTXlQNpJ1ub/B%C3%BCrokratt-Service-module-2023.03

### Acceptance Criteria

- [x] use Service Flow values as test values
- [x] every Service Element must contain editable test values
- [ ] button "Test service" appears for draft, inactive and active Services
- [x] by clicking on button "Test service", a Ruuter DSL is run with test input provided, #45 applied
- [ ] when drag-and-dropping Service Elements, they are automatically tested with their mock test inputs if not provided additionally -- _full flow not initiated, just testing this particular element_
- [ ] tested Service Elements are styled appropriately by using `!` in different color
- [ ] ~tested Service Elements are styled appropriately - background color green, orange, red, etc. Replaces #32~
- [ ] queries performed with #31 
- [ ] #91
- [ ] ~Ruuter response code sent to **EHA (to be developed)** to get a meaningful error message to be printed on a screen~
- [ ] #92
- [ ] All Elements should be live and working and when tested they should be tested with test data.
- [ ] Tested Service Elements are styled appropriately by using ! In case the element test fails or a tick if the element test succeeds

**Comment by turnerrainer** [comment]
@SigritSiht does it require making actual X-Road requests? If yes, then there will be a lot of X-Road services that do not have test services available.

**Comment by SigritSiht** [comment]
Can we enable it to make actual X-Road requests when the user enters their own (or team mates etc) credentials and is OK with the query? I'd like to keep this option open but have it be understood by the user that it will be a LIVE X-Road query not a TEST service (flag it on screen).
@turnerrainer

**Comment by turnerrainer** [comment]
> Can we enable it to make actual X-Road requests when the user enters their own (or team mates etc) credentials and is OK with the query? I'd like to keep this option open but have it be understood by the user that it will be a LIVE X-Road query not a TEST service (flag it on screen). @turnerrainer

@SigritSiht technically yes, in real life, no. Test is test and prod is prod, especially when it comes to X-road requests as it would be possible to use any personal code to make requests. And personal codes in Estonia are public information.

**Comment by turnerrainer** [comment]
@SigritSiht we can/should still keep this issue as it's not purely X-road-specific.

**Comment by SigritSiht** [comment]
@PaulaMerle and @turnerrainer  should this task be turnt to two different tasks? 
1. Entering mock key-value pairs for mocking the service for the service flow when test reply is not available.
2. Testing of the whole service flow which could turn out to be also many issues.
Because as of now this has kind of lost its point because #9 will kind of do it anyway?

**Comment by trevorling** [comment]
@turnerrainer 
`test results based on Ruuter logs`
Is this related to [#10](https://github.com/buerokratt/Service-Module/issues/10)?

**Comment by turnerrainer** [comment]
> @turnerrainer `test results based on Ruuter logs` Is this related to [#10](https://github.com/buerokratt/Service-Module/issues/10)?
> 
> What happens if the entire flow is untestable?

@trevorling 

Yes, it's related to https://github.com/buerokratt/Service-Module/issues/10.

What do you mean by the entire flow being untestable? You should also get input from the logs.

**Comment by allarlaaneleht** [comment]
@varmoh "Test service" send error code 300. 
[admin.play.buerokratt.ee test service error code 300.txt](https://github.com/buerokratt/Service-Module/files/12122524/admin.play.buerokratt.ee.test.service.error.code.300.txt)

**Comment by varmoh** [comment]
https://github.com/buerokratt/Service-Module/blob/ac7a1725498280410055131215219f675f716226/GUI/src/pages/ServiceFlowPage.tsx#L254
URL on hardcodetud mitte variable mistõttu, kui mul parasjagu Play keskkonnas puudub URL http://ruuter:8085 siis asi feilib

**Comment by allarlaaneleht** [comment]
@1AhmedYasser 
URLs are hard coded, but should be variables. "Test service" sends error code 300.

**Comment by allarlaaneleht** [comment]
@varmoh Please deploy the new update. (https://github.com/buerokratt/Service-Module/pull/135)

**Comment by allarlaaneleht** [comment]
1. Short summary: Tested service elements do not appear with different colour.
2. Expected result: Tested Service Elements are styled appropriately by using ! in different colour
3. Real result: Tested service elements are not styledin different colour
4. How to reproduce the bug: Create service flow, test the flow, add new elemets.
5. Pic or video:-

**Comment by allarlaaneleht** [comment]
1. Short summary: Testing service without  filling the mandatory information of elements gives success result.
2. Expected result: Service element without mandatory fields filled should not give a success result.
3. Real result: Service elements in service flow that do not have the necessary information added give success test result.
4. How to reproduce the bug: create service flow. Do not add information to elements, for example, rules, conversation or generate a file. Test the service.
5. Pic or video:-

**Comment by 1AhmedYasser** [comment]
> 1. Short summary: Tested service elements do not appear with different colour.
> 2. Expected result: Tested Service Elements are styled appropriately by using ! in different colour
> 3. Real result: Tested service elements are not styledin different colour
> 4. How to reproduce the bug: Create service flow, test the flow, add new elemets.
> 5. Pic or video:-

@turnerrainer this needs a modification on ruuter side to return in the response the status of the steps either failed or succeeded

**Comment by 1AhmedYasser** [comment]
> 1. Short summary: Testing service without  filling the mandatory information of elements gives success result.
> 2. Expected result: Service element without mandatory fields filled should not give a success result.
> 3. Real result: Service elements in service flow that do not have the necessary information added give success test result.
> 4. How to reproduce the bug: create service flow. Do not add information to elements, for example, rules, conversation or generate a file. Test the service.
> 5. Pic or video:-

@allarlaaneleht @turnerrainer Currently testing service are working and connected to ruuter, if you try adding a faulty endpoint or reference a variable that is not yet there, then it will fail. The bottom line here if ruuter returns 200 when testing the service yaml file it will return success otherwise it will return false.

**Comment by ValterAro** [comment]
Short summary: When adding a new service and during the service setup using the " + Lisa testkeskkond", the test environment is not saved. So when you go to the Service flow creation and then back then the test environment tab is gone.
Expected result: The test environment should be saved as is the Live endpoint.
Real result: When going back to the service setup from the Service flow creation then the added test environment is gone from the added endpoint.
How to reproduce the bug: create a service flow. During the Service setup add a live endpoint with the necessary info. Use the "+ Lisa testkeskkond" to add a test environment. Then go to the service flow creation step and go back or alternatively just refresh the page.
Pic or video:
![image](https://github.com/buerokratt/Service-Module/assets/122787093/2b3091bb-366a-4f2f-a384-2460045025fd)

**Comment by ValterAro** [comment]
Waiting for further developments as currently you can not test the full service and some of it is mocked.
As per Ahmed comment " 
           **Mocked:**
Tara Authentication (Mocked)
SIGA (Mocked)
Query Details response json (Mocked)
File Generation (Mocked)
File signing (Mocked)
Faulty Services (Mocked)
Testing A service (Parts of it are Mocked)
       **To be developed:**
Edit Service (To Be developed)
Manage Endpoints in one place (To be developed)
Common Endpoints used across all services (To be developed)
Common Services Managed by büerokratt (To be Developed)
Training a service fully to be ready to be used by bot and mange it from service module (Some of it are developed, but still needs further development)
Chatting with chatbot and triggering a service flow from start till end (To be Developed)
"

**Comment by ValterAro** [comment]
Short summary: When there is no options in the Setup elements box then there is no start where to drag and drop elements from All elements.
Expected result: you should be able to configure a service flow, even when there is no API endpoint configured for Setup elements.
Real result: there is no place to drag and drop elements
How to reproduce: Go to https://admin.dev.buerokratt.ee/services/overview and create a new service without configuring a custom endpoint.  Then in the last part where you create a service flow you can not even start a flow.
Pic:


![Image](https://github.com/buerokratt/Service-Module/assets/122787093/8dc9a9fc-bbf3-4033-919a-b84f74b1d1ef)

**Comment by ValterAro** [comment]
Short summary: The Acceptance criteria are not met. Visually I only see an "!", when the element needs some input or is not working, but there is no other indication that the element has been tested after being dragged to the flow. Also no chat widget integration in the "Test service" and also check the other AC.
How to reproduce: login and go to https://admin.dev.buerokratt.ee/services/overview and create a service and go to third step.
Pic:


![Image](https://github.com/buerokratt/Service-Module/assets/122787093/49fdc3d4-ec1b-4299-b28d-75a97ea3fa9c)

**Comment by turnerrainer** [comment]
Initial ETA Feb 20th, changed on march 8th.

**Comment by ValterAro** [comment]
Short summary: the chat widget is not integrated for testing the created service. There should be a popup chat window where you can see the service flow.
AC: https://github.com/buerokratt/Service-Module/issues/92

**Comment by PaulaMerle** [comment]
All GUI seems to be working according to ACs
