### ISSUE TITLE
Create Weather Service

### ISSUE THREAD

**Issue by 1AhmedYasser** [buerokratt/Service-Module#164]
AS An Administrative User / Service Manager
I WANT TO have common weather service
SO THAT the user can ask for weather in different countries all over the world 

### Acceptance Criteria

- [ ] [Create A Common service](https://github.com/buerokratt/Service-Module/issues/12)
- [ ] [Create and manage the weather endpoints when creating the service](https://github.com/buerokratt/Service-Module/issues/12)
- [ ] [Link Intents to services]()
- [ ] Upon service success return the weather to the user
- [ ] [Upon service failure respond with appropriate message to the user and report the failure to faulty services](https://github.com/buerokratt/Service-Module/issues/10)
- [ ] [Edit the service to add new weather info](https://github.com/buerokratt/Service-Module/issues/142)

**Comment by turnerrainer** [comment]
Will be re-factored in #71
