### ISSUE TITLE
Create conversation scripts to get user input

### ISSUE THREAD

**Issue by SigritSiht** [buerokratt/Service-Module#18]
AS A Service Manager
I WANT TO create conversation scripts
SO THAT I CAN get the user input needed for queries

### Acceptance Criteria

- [ ] Use #20 to create conversation scripts
- [ ] Intent detection by OpenSearch, see #19 for details
- [ ] Based on [Rasa rules](https://rasa.com/docs/rasa/rules)
- [ ] Stateless in the sense of not storing the state of a conversation as Rasa story would
- [ ] Define the maximum amount of asking the client to provide additional input for the same step _(for example, to provide information about location)_ as a generic setting applied to all Services _(in "Settings" in GUI)_

`intents`
- [ ] A Rasa NLU file has to exist for every `intent` used in a rule, even if it's empty
- [ ] Intents used must be defined in [Rasa domain file](https://github.com/buerokratt/Training-Module/blob/main/mock1/domain.yml#L3-L13)

`actions`
- [ ] A [Rasa domain file](https://github.com/buerokratt/Training-Module/blob/main/mock1/domain.yml#L56-L117) has to include every response used in a rule

#### Sample services

> The following sample services must be created

> A sample Service to rent a car in Tallinn, Estonia, on a specified date within a specified time period

- [ ] Happy path test, where the user's initial input covers everything required by the Service
- [ ] Happy path test, where the user's input covers everything required by the Service by the user providing additional input step-by-step
- [ ] Unhappy path, where the user is just mocking around and the Services' loop has to be ended

### Examples

https://github.com/buerokratt/Service-Module/issues/18#issuecomment-1484582578 by @KlviG 

From RASA's point of view

If the service is only 1 step, then the previous doc applies.

```yaml
rule: service_car_rent
  steps:
    intent: service_car_rent
    action: utter_service_car_rent
```

If the service requires additional input from the user, then extra steps will be included in the same rule.

```yaml
rule: service_car_rent
  steps:
    intent: service_car_rent
    action: utter_service_car_rent
    intent: service_car_rent_country
    action: utter_service_car_rent_country
    intent: service_car_rent_city
    action: utter_service_car_rent_city
```

**Comment by SigritSiht** [comment]
scripts will be created on #20

**Comment by turnerrainer** [comment]
@SigritSiht should this issue have a number of services as part of AC that need to be provided?

**Comment by SigritSiht** [comment]
AC:

- [ ] based on [Rasa stories](https://rasa.com/docs/rasa/stories)

will most likely be changed to [Rasa rules](https://rasa.com/docs/rasa/rules) because rules are in broad terms less "sophisticated" stories.

Rules must be able to "break", i.e it cannot be a endless loop of trying to get input from the end-user.

**Comment by SigritSiht** [comment]
@KlviG @turnerrainer do we even need Rasa rules? if we use #19 logic to understand a user.

**Comment by KlviG** [comment]
From RASA point of view:
If service is only 1 step, then previous doc applies.
- rule: service_car_rent
  steps:
  - intent: service_car_rent
  - action: utter_service_car_rent

If service requires additional input from user, then extra steps will be included on the same rule.
  - intent: service_car_rent
  - action: utter_service_car_rent
  - intent: service_car_rent_country
  - action: utter_service_car_rent_country
  - intent: service_car_rent_city
  - action: utter_service_car_rent_city
