### ISSUE TITLE
Extract and label data based on user input

### ISSUE THREAD

**Issue by SigritSiht** [buerokratt/Service-Module#19]
AS AN Architect
I WANT TO have a REST service to label input and/or parts of it
SO THAT I wouldn't have duplicate developments for that

> Depends on https://github.com/buerokratt/Training-Module/issues/25

### Acceptance Criteria

> ETL pipeline to fetch data from Rasa to OpenSearch is out of scope of this issue

- [ ] REST endpoint `/label` using POST parameters as input
- [ ] User input is matched and grouped by pre-defined entities

### Examples

**Expected user input and output based on it**

- [ ] Input _"What's the weather like in Tallinn?"_ results in `[SERVICE] weather` + `[LOC] Tallinn`
- [ ] Input _"Tallinn weather"_ results in `[LOC] Tallinn` + `[SERVICE] weather`
- [ ] Input _"Tallinn weather and what's up"_ results in `[LOC] Tallinn` + `[SERVICE] weather` + `[UNCLASSIFIED] and what's up`

**OpenSearch indices with mock data based on Rasa examples**

- [ ] https://github.com/buerokratt/Training-Module/tree/main/mock1/data/nlu for intents
- [ ] https://github.com/buerokratt/Training-Module/blob/main/mock1/data/regex_nlu.yml for locations
- [ ] As a result, group inputs based on their characteristics (`LOCATION`, `SERVICE`, etc.)

> See https://en.wikipedia.org/wiki/Declension

#### GUI

- [ ] Based on an existing [Training Module's GUI view](http://test.buerokratt.ee:3002/treening/treening/teemade-jareltreenimine) functionality
- [ ] Combine ["Entities / Olemid"](http://test.buerokratt.ee:3002/treening/treening/teemade-jareltreenimine) and [REGEX examples](http://test.buerokratt.ee:3002/treening/treening/teemade-jareltreenimine) as 1 view
- [ ] Instead of regex examples, regular strings are used

#### DSL

- [ ] Based on OpenSearch
- [ ] #73
- [ ] Download examples as CSV (use an existing Ruuter and Data Mapper DSLs - see [here](http://test.buerokratt.ee:3010/analytics/chats) and [here](https://github.com/buerokratt/Training-Module/issues/25) for more)

**Comment by turnerrainer** [comment]
@SigritSiht

1. User asks for information about current weather;
2. Bürokratt asks the user to specify the location they are interested in;
3. User responds with "Tallinn";
4. **The intent of this issue** is to send "Tallinn" to additional processing before passing it on to the chatbot (Rasa)? Am I correct?

**Comment by SigritSiht** [comment]
@turnerrainer correct, but also consider not just Tallinnas - > Tallinn use case, but Tallinna linnas etc other words that may be added by the user that have no value w.r.t the query.

**Comment by turnerrainer** [comment]
> @turnerrainer correct, but also consider not just Tallinnas - > Tallinn use case, but Tallinna linnas etc other words that may be added by the user that have no value w.r.t the query.

@SigritSiht Got it, sounds good.

**Comment by 1AhmedYasser** [comment]
@turnerrainer @SigritSiht 

Regarding My Input on Open Search Possibility to process multiple keywords using NLP:-

* You Can Query an index (i.e. DB) using a simple NLP query

   - https://opensearch.org/docs/latest/opensearch/query-dsl/full-text/index#query-string

* Also Open Search Supports Different types of query DSL's 

   - https://opensearch.org/docs/latest/opensearch/query-dsl/index

* When you enter your query you can specify an option to highlight all matching field's and open search offers a lot of options for it as well
    - https://opensearch.org/docs/latest/opensearch/search/highlight/
    
- Example Request Query
```
POST opensearch_dashboards_sample_data_ecommerce/_search
{
  "query": {
    "query_string": {
      "query": "Is there a girl named mary here"
    }
  },
  "highlight": {
    "require_field_match": "false", 
    "fields": {
      "*": {}
    }
  }
}
```

- Example Response
```
{
  "took": 50,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 154,
      "relation": "eq"
    },
    "max_score": 3.5671005,
    "hits": [
      {
        "_index": "opensearch_dashboards_sample_data_ecommerce",
        "_id": "vxxqs4YBxJo3V4jW-u0Z",
        "_score": 3.5671005,
        "_source": {
          "category": [
            "Women's Clothing"
          ],
          "currency": "EUR",
          "customer_first_name": "Mary",
          "customer_full_name": "Mary Reyes",
          "customer_gender": "FEMALE",
          "customer_id": 20,
          "customer_last_name": "Reyes",
          "customer_phone": "",
          "day_of_week": "Wednesday",
          "day_of_week_i": 2,
          "email": "mary@reyes-family.zzz",
          "manufacturer": [
            "Pyramidustries active",
            "Crystal Lighting"
          ],
          "order_date": "2023-03-22T22:00:29+00:00",
          "order_id": 588016,
          "products": [
            {
              "base_price": 16.99,
              "discount_percentage": 0,
              "quantity": 1,
              "manufacturer": "Pyramidustries active",
              "tax_amount": 0,
              "product_id": 23791,
              "category": "Women's Clothing",
              "sku": "ZO0224502245",
              "taxless_price": 16.99,
              "unit_discount_amount": 0,
              "min_price": 9.34,
              "_id": "sold_product_588016_23791",
              "discount_amount": 0,
              "created_on": "2016-12-28T22:00:29+00:00",
              "product_name": "Tights - black",
              "price": 16.99,
              "taxful_price": 16.99,
              "base_unit_price": 16.99
            },
            {
              "base_price": 41.99,
              "discount_percentage": 0,
              "quantity": 1,
              "manufacturer": "Crystal Lighting",
              "tax_amount": 0,
              "product_id": 21101,
              "category": "Women's Clothing",
              "sku": "ZO0484604846",
              "taxless_price": 41.99,
              "unit_discount_amount": 0,
              "min_price": 22.67,
              "_id": "sold_product_588016_21101",
              "discount_amount": 0,
              "created_on": "2016-12-28T22:00:29+00:00",
              "product_name": "Soft shell jacket - grey multicolor",
              "price": 41.99,
              "taxful_price": 41.99,
              "base_unit_price": 41.99
            }
          ],
          "sku": [
            "ZO0224502245",
            "ZO0484604846"
          ],
          "taxful_total_price": 58.98,
          "taxless_total_price": 58.98,
          "total_quantity": 2,
          "total_unique_products": 2,
          "type": "order",
          "user": "mary",
          "geoip": {
            "country_iso_code": "AE",
            "location": {
              "lon": 55.3,
              "lat": 25.3
            },
            "region_name": "Dubai",
            "continent_name": "Asia",
            "city_name": "Dubai"
          },
          "event": {
            "dataset": "sample_ecommerce"
          }
        },
        "highlight": {
          "customer_full_name": [
            "<em>Mary</em> Reyes"
          ],
          "customer_first_name": [
            "<em>Mary</em>"
          ],
          "user": [
            "<em>mary</em>"
          ]
        }
      },
      etc ...
```

**Comment by SigritSiht** [comment]
Blocked because of #73

**Comment by turnerrainer** [comment]
As @1AhmedYasser pointed out, this issue belongs to Training Module
