### ISSUE TITLE
Service Module Creating Service Flow Page

### ISSUE THREAD

**Issue by SigritSiht** [buerokratt/Service-Module#20]
AS AN Administrative User
I WANT TO pick various elements previously created or predefined (query connections, final utterance, user input/output fields, TARA, SiGA etc)
SO THAT I CAN assemble the service flow

> This issue is to finalize a Service with the input provided by https://github.com/buerokratt/Service-Module/issues/12

> ~Use https://xd.adobe.com/view/cb1ca0df-2dea-4432-a05d-bb75db6e2e5f-9e4f as GUI reference instead of the images added in comments~

#### GUI

- [x] Based on [Figma example](https://www.figma.com/file/yF3ywx7OaufCTXlQNpJ1ub/B%C3%BCrokratt-Service-module-2023.03?node-id=15-24018)
- [x] Service name and description initially displayed on screen _(currently missing on GUI mock)_
- [x] Blocks can be collapsed (minimize, maximize)
- [x] Service elements on the left of the GUI can be drag-and-dropped to create a Service flow
- [ ] ~Under "Settings", a generic response to provide in case of errors / exceptions (#EHA settings) can be added and updated~
- [x] Button "Continue with training the Service", takes to #11
- [x] Button "Save as Draft" created, takes to #11
- [x] Changes to Service DSLs are triggered after pressing the "Save Service" (or similar) button

#### DSL

- [ ] ~#50 is used to provide error / exception (#EHA) responses for End Users (use Ruuter's functionality and EHA concept)~
> ~#EHA scope within this project is to have a proper GUI and static response from back-end (JSON served by Nginx, for example)~
- [x] #21
- [ ] #13 
- [ ] ~geolocation element (enabling sharing of end-users location) can be added to service flow~
- [ ] #5
- [x] #16
- [ ] A Service created can be saved as a draft Service by using #41 

> **Comment:** The `return` section of the Ruuter DSL of a created service has to be manipulatable via GUI by adding static text and any number of output in any order from previous steps of the same Ruuter DSL.

**Comment by SigritSiht** [comment]
![Image](https://user-images.githubusercontent.com/25658198/196414297-e8171b18-ec09-46cc-b0fe-33c33f6ddb10.png)

**Comment by SigritSiht** [comment]
![Image](https://user-images.githubusercontent.com/25658198/196414408-a6e51a3a-9d02-4909-8d28-fe266e8ee6e8.png)

**Comment by turnerrainer** [comment]
@SigritSiht should be covered by D&D GUI developments.

I'll label it as obsolete at the moment but don't delete it yet.

**Comment by SigritSiht** [comment]
@turnerrainer this is back to ToDo because #6 and #20 are now combined and this new task should be reexamined.

**Comment by turnerrainer** [comment]
**The Services on the left** are created via #12 - dynamic Services with potentially any kind of endpoints.

**The Services on the right** are Ruuter Sticky Services (see #37 for an example)

**Comment by SigritSiht** [comment]
New and improved pictures that reflect all ACs

https://xd.adobe.com/view/cb1ca0df-2dea-4432-a05d-bb75db6e2e5f-9e4f/

**Comment by SigritSiht** [comment]
> Blocked as needs further discussion regarding to training Rasa models -- input from @vmugra and @KlviG needed

Discussed with the BYK team and AC 

- [ ] Button ("Continue with training the Service") created, takes to Training Module's functionality to train a new model
is probably going to change to direct user to #11 and provide a notification "Model will be automatically trained on XXXday" if agency has set an automated training process to take place or "Model needs to be trained" if agency does not have an automated process in place.

**Comment by SigritSiht** [comment]
TBD by @turnerrainer but Rasa rules should be created in this view but using the same elements etc. as are in use for the Training Module.

TBD by @turnerrainer but Service can also just be assembled URLs not only queries for Ruuter. (ex. RaRa)

**Comment by SigritSiht** [comment]
First look of UX done, still needs a bit of work.

**Comment by SigritSiht** [comment]
Automatic save trigger is missing as an AC, needed so user's done work would remain as Draft.

**Comment by trevorling** [comment]
@turnerrainer 
[Figma link](https://www.figma.com/file/yF3ywx7OaufCTXlQNpJ1ub/B%C3%BCrokratt-Service-module-2023.03?node-id=15%3A24018&t=vdBx56D1YzTBtOiD-1)

**Comment by turnerrainer** [comment]
GUI-blocked

**Comment by allarlaaneleht** [comment]
BUG: Button "Save as Draft" created, does not take to https://github.com/buerokratt/Service-Module/issues/11 .
Nothing happens if the button is pushed.

**Comment by allarlaaneleht** [comment]
BUG: Created service cannot be saved. After clicking on "continue" you will be directed to services landing page, created service does not appear.

**Comment by allarlaaneleht** [comment]
BUG: No TARA endpoint values displayed
![Tara valjundelemendid puuduvad](https://github.com/buerokratt/Service-Module/assets/139747282/2341af6e-dc36-4f65-93af-9b953e1ff3ee)
 when creating a service flow.

**Comment by 1AhmedYasser** [comment]
> BUG: Button "Save as Draft" created does not take to #11 . Nothing happens if the button is clicked on.

@allarlaaneleht Save as draft now creates the service as draft and the reason it does not take you to 11 is that you may need to test it first or change something before pressing on continue and moving on to 11, if would make save as draft go to #11 directly then the service admin won't be able to test the service first or test the components, what do you think ?

**Comment by 1AhmedYasser** [comment]
> 

@allarlaaneleht this behaviour is glitchy, you should always save as draft first before publishing the service, i modified the flow to prevent you from pressing continue on the last step before you have saved it as draft and the test button is shown to you

**Comment by 1AhmedYasser** [comment]
> BUG: No TARA endpoint values displayed when creating a service flow. ![Tara valjundelemendid puuduvad](https://user-images.githubusercontent.com/139747282/259933148-2341af6e-dc36-4f65-93af-9b953e1ff3ee.png)

@allarlaaneleht  Added Tara Secrets, but currently all secrets are defined inside the yml files, but i think there should be a panel to change the secrets values other than inside the codebase, for now the added secrets are containing mock values, and these values should be changed somehow from the GUI by the service admin, what do you think ?

**Comment by allarlaaneleht** [comment]
@1AhmedYasser @varmoh Saving the draft still does not seem to be working. The service won't appear in the services list after saving the draft. Could you please take a look at this.

**Comment by allarlaaneleht** [comment]
1. Short summary: User cannot either scroll the page or zoom in and out to have an overview of the service flow.
2. Expected result: User should be able to zoom in and out the service flow iot have and overview of the flow.
3. Real result: the page is not zoomable or scrollable.
4. How to reproduce the bug: create the service flow.
5. Pic or video: -

**Comment by allarlaaneleht** [comment]
1. Short summary: Service can be saved without naming it.
2. Expected result: Service's name and description should be obligatory fields to be filled.
3. Real result: One can save the service without filling services name and description.
4. How to reproduce the bug: create a service without naming it, save it.
5. Pic or video:-

**Comment by allarlaaneleht** [comment]
1. Short summary: User cannot add a new element in the middle of the flow.
2. Expected result: User should be able to add a new element in the middle of the flow if needed. At the moment, one should delete the existing flow to the point where the new element needs to be added.
3. Real result: User can only add new element as the last element of the flow.
4. How to reproduce the bug: Create a service flow. Try to add a new element in between already added elements.
5. Pic or video: https://drive.google.com/file/d/1nuekuIfzDq5tQKsZ0X6AUSnZENm8TY_i/view?usp=sharing (from 00:00 to 00:12)

**Comment by allarlaaneleht** [comment]
1. Short summary: The "add a new element" box in the service flow can be dragged/moved in between already added elements. When it is moved to the position where the arrows (and lines) match (cannot tell if they are merged or user just sees one line, but actually two of them exist which you cannot see). Now, when for example, "end the conversation" element is added between other elements, flow test is still successful. 
2. Expected result: There should not be an opportunity to have menu elements after final elements (end the conversation and forward to customer support)
3. Real result: "Ending" or "final" elements can be added between other elements, test result will be still successful.
4. How to reproduce the bug: see the video.
5. Pic or video: https://drive.google.com/file/d/14_R2OajnWHUhftuhKttmIrEcV8dFD48L/view?usp=sharing

**Comment by allarlaaneleht** [comment]
1. Short summary: When elements are moved around, flow arrows break and connective flow breaks. 
2. Expected result: Lines and arrows should not break when elements are moved around.
3. Real result: Connective lines between flow elements can break. 
4. How to reproduce the bug: Create a service flow, move the elements around.
5. Pic or video: https://drive.google.com/file/d/1Rt40iZiWMvq-CetZZW1eQC2yiMwXLZQX/view?usp=sharing

**Comment by allarlaaneleht** [comment]
1. Short summary: Hovering over the flow elements creates arrows and lines that lead nowhere.
2. Expected result: The connective lines between the flow elements should not break. 
3. Real result: Hovering over the flow elements creates arrows and lines that lead nowhere-
4. How to reproduce the bug: create a service flow, hover over the flow elements. See the video from 00:00:12 to 00:00:30
5. Pic or video: https://drive.google.com/file/d/1nuekuIfzDq5tQKsZ0X6AUSnZENm8TY_i/view?usp=sharing

**Comment by allarlaaneleht** [comment]
1. Short summary: The flow items can be moved so they cover another flow element.
2. Expected result: The flow elements should not be able to cover other elemets.
3. Real result: The flow element can be moved so the text from other element is covered by another flow element.
4. How to reproduce the bug: See the video from 00:01:00 to 00:01:15
5. Pic or video: https://drive.google.com/file/d/1nuekuIfzDq5tQKsZ0X6AUSnZENm8TY_i/view?usp=sharing

**Comment by allarlaaneleht** [comment]
1. Short summary: Service description is not displayed on service flow page.
2. Expected result: Service name and description initially displayed on screen.
3. Real result: Only service name is displayed on the screen.
4. How to reproduce the bug: Fill in the service name and description, go to the service flow page.
5. Pic or video:-

**Comment by 1AhmedYasser** [comment]
> 1. Short summary: Hovering over the flow elements creates arrows and lines that lead nowhere.
> 2. Expected result: The connective lines between the flow elements should not break.
> 3. Real result: Hovering over the flow elements creates arrows and lines that lead nowhere-
> 4. How to reproduce the bug: create a service flow, hover over the flow elements. See the video from 00:00:12 to 00:00:30
> 5. Pic or video: https://drive.google.com/file/d/1nuekuIfzDq5tQKsZ0X6AUSnZENm8TY_i/view?usp=sharing

Could not replicate on local side, can you recheck from dev side or provide a detailed steps to reproduce this issue

**Comment by 1AhmedYasser** [comment]
> 1. Short summary: When elements are moved around, flow arrows break and connective flow breaks.
> 2. Expected result: Lines and arrows should not break when elements are moved around.
> 3. Real result: Connective lines between flow elements can break.
> 4. How to reproduce the bug: Create a service flow, move the elements around.
> 5. Pic or video: https://drive.google.com/file/d/1Rt40iZiWMvq-CetZZW1eQC2yiMwXLZQX/view?usp=sharing

Could not replicate on local side, can you recheck from dev side or provide a detailed steps to reproduce this issue

**Comment by 1AhmedYasser** [comment]
> 1. Short summary: The "add a new element" box in the service flow can be dragged/moved in between already added elements. When it is moved to the position where the arrows (and lines) match (cannot tell if they are merged or user just sees one line, but actually two of them exist which you cannot see). Now, when for example, "end the conversation" element is added between other elements, flow test is still successful. In conclusion, When the illogical service is created, then you get success message (or the arrows no not present the actual flow).
> 2. Expected result: There should not be an opportunity to have menu elements after final elements (end the conversation and forward to customer support)
> 3. Real result: "Ending" or "final" elements can be added between other elements, test result will be still successful.
> 4. How to reproduce the bug: see the video.
> 5. Pic or video: https://drive.google.com/file/d/14_R2OajnWHUhftuhKttmIrEcV8dFD48L/view?usp=sharing

Could not replicate on local side, can you recheck from dev side or provide a detailed steps to reproduce this issue

**Comment by 1AhmedYasser** [comment]
> 1. Short summary: User cannot add a new element in the middle of the flow.
> 2. Expected result: User should be able to add a new element in the middle of the flow if needed. At the moment, one should delete the existing flow to the point where the new element needs to be added.
> 3. Real result: User can only add new element as the last element of the flow.
> 4. How to reproduce the bug: Create a service flow. Try to add a new element in between already added elements.
> 5. Pic or video: https://drive.google.com/file/d/1nuekuIfzDq5tQKsZ0X6AUSnZENm8TY_i/view?usp=sharing (from 00:00 to 00:12)

@allarlaaneleht This was not mentioned in the AC, so there is not present in the codebase at the current time and will require extra development to achieve it on the GUI and DSL sides

**Comment by 1AhmedYasser** [comment]
> 1. Short summary: The flow items can be moved so they cover another flow element.
> 2. Expected result: The flow elements should not be able to cover other elemets.
> 3. Real result: The flow element can be moved so the text from other element is covered by another flow element.
> 4. How to reproduce the bug: See the video from 00:01:00 to 00:01:15
> 5. Pic or video: https://drive.google.com/file/d/1nuekuIfzDq5tQKsZ0X6AUSnZENm8TY_i/view?usp=sharing

This will be added as a GUI improvement, not a bug fix, will investigate its possibility on react flow side

**Comment by 1AhmedYasser** [comment]
@allarlaaneleht 

Enhancements added:

1. Save Draft in 2nd step can now save endpoints for later use In service editing
2. Added Local validation to the following steps (Send Message to client, Client Input, Open new website, file generation) and the rest is still in mock state
3. After you save draft in the flow page then the test service button appears and if you now make new changes the test service button will be disabled until you save the new changes

**Comment by 1AhmedYasser** [comment]
> 1. Short summary: User cannot either scroll the page or zoom in and out to have an overview of the service flow.
> 2. Expected result: User should be able to zoom in and out the service flow iot have and overview of the flow.
> 3. Real result: the page is not zoomable or scrollable.
> 4. How to reproduce the bug: create the service flow.
> 5. Pic or video: -

Fixed

**Comment by 1AhmedYasser** [comment]
> 1. Short summary: Service can be saved without naming it.
> 2. Expected result: Service's name and description should be obligatory fields to be filled.
> 3. Real result: One can save the service without filling services name and description.
> 4. How to reproduce the bug: create a service without naming it, save it.
> 5. Pic or video:-

Fixed

**Comment by 1AhmedYasser** [comment]
> 1. Short summary: The flow items can be moved so they cover another flow element.
> 2. Expected result: The flow elements should not be able to cover other elemets.
> 3. Real result: The flow element can be moved so the text from other element is covered by another flow element.
> 4. How to reproduce the bug: See the video from 00:01:00 to 00:01:15
> 5. Pic or video: https://drive.google.com/file/d/1nuekuIfzDq5tQKsZ0X6AUSnZENm8TY_i/view?usp=sharing

Fixed

**Comment by 1AhmedYasser** [comment]
> 1. Short summary: Service description is not displayed on service flow page.
> 2. Expected result: Service name and description initially displayed on screen.
> 3. Real result: Only service name is displayed on the screen.
> 4. How to reproduce the bug: Fill in the service name and description, go to the service flow page.
> 5. Pic or video:-

Fixed

**Comment by allarlaaneleht** [comment]
Short summary: Text on blue buttons not readable.
Expected result: Readable text.
Real result: Text not visible.
How to reproduce the bug: open page, see the buttons.
Pic or video: 
![image](https://github.com/buerokratt/Service-Module/assets/139747282/9dff2164-647a-4ad2-9580-cdffe50a1f34)

**Comment by allarlaaneleht** [comment]
Short summary: Cannot save the flow as a draft.
Expected result: Service draft saved.
Real result: Error message.
How to reproduce the bug: See the video.
Pic or video: https://drive.google.com/file/d/1X7J7DqV-w-uBmiVeHkJn4SYg8sdAoIkx/view?usp=sharing

**Comment by allarlaaneleht** [comment]
Short summary: Refreshing the page creates new boxes to the flow.
Expected result: Refreshing the page should not do anything.
Real result: New boxes for new elements appear after refreshing the page.
How to reproduce the bug: See the video from 0:15
Pic or video: https://drive.google.com/file/d/1X7J7DqV-w-uBmiVeHkJn4SYg8sdAoIkx/view?usp=sharing

**Comment by turnerrainer** [comment]
AT rejected possibly due to third-party commits according to @1AhmedYasser

**Comment by 1AhmedYasser** [comment]
> Short summary: Text on blue buttons not readable. Expected result: Readable text. Real result: Text not visible. How to reproduce the bug: open page, see the buttons. Pic or video: ![image](https://user-images.githubusercontent.com/139747282/273902892-9dff2164-647a-4ad2-9580-cdffe50a1f34.png)

Will have a PR from @ExiRain to fix it on header styles

**Comment by allarlaaneleht** [comment]
Short summary: Cannot save the flow as a draft.
Expected result: Service draft saved.
Real result: Save button is unresponsive.
How to reproduce the bug: Create service flow, try to save it.
Pic or video: -

**Comment by 1AhmedYasser** [comment]
@allarlaaneleht Added a fix to node server which is merge, which in some cases didn't allow the service to be saved, please recheck it

**Comment by ValterAro** [comment]
Short summary: When creating a service in the https://admin.dev.buerokratt.ee/services/newService and then get to the third stage https://admin.dev.buerokratt.ee/services/flow , then you can save the service by pressing "Salvesta mustandina" multiple times and every time it creates a new entry in the https://admin.dev.buerokratt.ee/services/overview list. 
Expected result: The old service with the same name is overwritten
Real result: A new service is created in the list with the same name
How to reproduce: written in the summary

Pic:


![Image](https://github.com/buerokratt/Service-Module/assets/122787093/c081b639-3ea8-4b61-b558-7bbbac067401)

List of multiple entries

![Image](https://github.com/buerokratt/Service-Module/assets/122787093/ac0259df-e26e-4d60-bc2a-94bb0ab5b9b5)

**Comment by rasmusei** [comment]
@ValterAro why is this task blocked?

**Comment by ValterAro** [comment]
@rasmusei The problem was that some of the responses were mocked and the service creation flow could not be properly tested. During the last two weeks there was a PR to fix some of it (https://github.com/buerokratt/Service-Module/pull/172), but now the main problem is that the whole service module can not really be tested as the admin.dev.buerokratt is not properly working.

**Comment by ValterAro** [comment]
Short summary: Unable to save a service flow when pressing the "salvesta mustandina" button
Expected result: The UI shows a popup of a succesful creation of a service.
Real result: It shows that the creation failed
How to replicate: Go to https://admin.dev.buerokratt.ee/services/flow , create a service and try to save it.
Pic:


![Image](https://github.com/buerokratt/Service-Module/assets/122787093/fc9e122f-642a-4425-9af8-c3eb820abfc3)

**Comment by 1AhmedYasser** [comment]
> Short summary: Unable to save a service flow when pressing the "salvesta mustandina" button Expected result: The UI shows a popup of a succesful creation of a service. Real result: It shows that the creation failed How to replicate: Go to https://admin.dev.buerokratt.ee/services/flow , create a service and try to save it. Pic:
> 
> ![Image](https://private-user-images.githubusercontent.com/122787093/295942794-fc9e122f-642a-4425-9af8-c3eb820abfc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NTExNTYsIm5iZiI6MTcwNTQ1MDg1NiwicGF0aCI6Ii8xMjI3ODcwOTMvMjk1OTQyNzk0LWZjOWUxMjJmLTY0MmEtNDQyNS05YWY4LWMzZWI4MjBhYmZjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExN1QwMDIwNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDUyNTZiYWJkMmEwNjYwNmMxZDNlNzUzYTgyODM0YWJlMzM1ZTNkNTg2NmQ4NmI4N2IzMzk1NjE4M2RkMWE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.w0uACkhXawOKZsjpdj2FRqiyjU6AgNVAoXpLsKrMSJs)

@ValterAro Could not replicate it on dev environment at current state, can you please recheck, and if it still presists, then lets have a meeting about it

**Comment by ValterAro** [comment]
It worked also yesterday. Must have been fixed on the deployment side then on Monday.

**Comment by ValterAro** [comment]
Short summary: When adding the Client input step to the service flow, then this step does not have the options it had previously. There should be an option to make it a yes/no input and some additional things.
Expected result: You should be given options to configure the Client input
Real result: the Setup for client input is empty
How to reproduce: login and go to https://admin.dev.buerokratt.ee/services/overview . Then create a new service and at the Service flow creation try to add Client input step and try to do edit it.
Pic:
![image](https://github.com/buerokratt/Service-Module/assets/122787093/fa60e83b-63ab-4fa4-8b3c-65a4e13bcf7e)

**Comment by 1AhmedYasser** [comment]
> Short summary: When adding the Client input step to the service flow, then this step does not have the options it had previously. There should be an option to make it a yes/no input and some additional things. Expected result: You should be given options to configure the Client input Real result: the Setup for client input is empty How to reproduce: login and go to https://admin.dev.buerokratt.ee/services/overview . Then create a new service and at the Service flow creation try to add Client input step and try to do edit it. Pic: ![image](https://private-user-images.githubusercontent.com/122787093/301440995-fa60e83b-63ab-4fa4-8b3c-65a4e13bcf7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNTAyNDIsIm5iZiI6MTcwNzI0OTk0MiwicGF0aCI6Ii8xMjI3ODcwOTMvMzAxNDQwOTk1LWZhNjBlODNiLTYzYWItNGZhNC04YjNjLTY1YTRlMTNiY2Y3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQyMDA1NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjc0ZWYzODE3ZGIwMzU3OTFkZjAwYjFjNGYxNGY3MTQyMWRkYWUzYzkzNzI4MjFiMTdjNTAzZmIzZjliOTgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vcp3hH61uLZ51TvVtfpz9v-m8Faoo1y5E9xNQj_UdH8)

is this related to https://github.com/buerokratt/Service-Module/issues/182#issuecomment-1920778454 ? does this still presists

**Comment by ValterAro** [comment]
@1AhmedYasser  I think it is separate from #182 . There used to be a yes/no option for this whether it is a yes no question with a text box where to write the question. 
Pic from figma:


![Image](https://github.com/buerokratt/Service-Module/assets/122787093/c2ddf01b-d342-404e-b04f-c9669c5ce2e7)

**Comment by ValterAro** [comment]
Seems to work as intended

**Comment by ValterAro** [comment]
Fix for the Response not showing when checking the JSON request. https://github.com/buerokratt/Service-Module/issues/182#issuecomment-1920778454

**Comment by ValterAro** [comment]
Short summary: When creating a service flow and using the element for client input then there is no option to add the next element
Real result: You can not add a element after the client input element
Expected result: Only the End conversation and send to csa should be terminating elements
How to reproduce: login and go to https://admin.dev.buerokratt.ee/services/overview , then try to create or edit a service and in the service flow step add a client input. 
Additional info: Also there should be two paths out when the option is for a Yes/NO question.
Pic:


![Image](https://github.com/buerokratt/Service-Module/assets/122787093/75f0cf1e-7535-4a25-a954-684be1826596)

**Comment by ValterAro** [comment]
Short summary: You get an error when trying to save a service flow that has a client input in it. Tried with "yes/no" question and the rule based approach for the client input
expected result: You should be able to save the service flow with the client input element
How to reproduce: login and try to create a new service. Then at the third step add a client input and try to save the service flow. You will see an error popup.
Pic:


![Image](https://github.com/buerokratt/Service-Module/assets/122787093/e7fd23b5-1fb8-4b88-b3d4-75280c4780a2)
