### ISSUE TITLE
GUI-based Service conditions manipulation

### ISSUE THREAD

**Issue by SigritSiht** [buerokratt/Service-Module#21]
AS A Service Manager
I WANT TO create Ruuter DSL-based services by using a GUI
SO THAT I wouldn't have to know Ruuter DSL syntax to create Services

> https://xd.adobe.com/view/cb1ca0df-2dea-4432-a05d-bb75db6e2e5f-9e4f/screen/fff5de82-8d66-4563-ae2e-a49214039214 as reference mock GUI

#### Steps

- [ ] Every section in GUI represents a step in Ruuter DSL

> See https://github.com/buerokratt/Ruuter/blob/main/samples/general/steps.md for reference

![image](https://user-images.githubusercontent.com/90505798/220871706-09f00996-e430-4718-b58d-bb5dffefa2b2.png)

#### Conditional operators

- [ ] [A list of pre-defined operators](https://www.w3schools.com/js/js_comparisons.asp) can be called out as GUI-based elements
- [ ] #51 _to cover mathematical, etc. rules (i.e. `if 05.01.2010 >= var childs_age`)_
- [ ] In addition, `in_array` operator is added
- [ ] Possibility to use mathematical operations in if statement: `if (response - number) >= than (number)`
- [ ] Comparable value can be taken as variable from user input: `if (response) == (user input)`

#### Conditional switch

- [ ] You can use just 1 condition to validate (and proceed if `OK`)

> See https://github.com/buerokratt/Ruuter/blob/main/DSL/GET/scripting/conditional.yml as an example

![image](https://user-images.githubusercontent.com/90505798/220874225-2faa96f6-465e-4932-adf8-010ac2b7d3b4.png)

The above is similar to _(GUI and Ruuter DSL examples don't match)_

```json
first_step:
  return: ${CustomerServiceList >= 1}
```

as a Ruuter DSL

- [ ] Multiple conditional switches can be added

> See https://github.com/buerokratt/Ruuter/blob/main/DSL/GET/steps/switch/conditional-jump.yml#L7-L13 as an example

![image](https://user-images.githubusercontent.com/90505798/220874506-7d8a8e66-f5ff-4f95-ba31-89bcc9ae36a0.png)

The above is similar to _(GUI and Ruuter DSL examples don't match)_

```json
conditionalSwitch:
  switch:
    - condition: ${CustomerServiceList >= 1}
      next: teil_on_sellised_teenused
    - condition: ${CustomerServiceList == 1}
      next: teil_on_teenus
```

as a Ruuter DSL

**Comment by SigritSiht** [comment]
@PaulaMerle palun täienda kontrollide loendit AC-s

**Comment by turnerrainer** [comment]
@SigritSiht we haven't covered such business requirements yet but should do it as a generic functionality.

**Comment by turnerrainer** [comment]
@SigritSiht we can create Javascript-based rules within Ruuter DSLs. Would this cover the requirement for this issue?

**Comment by SigritSiht** [comment]
<html>
<body>


Operator | Description | Comparing | Returns | Try it
-- | -- | -- | -- | --
== | equal to | x == 8 | false | Try it »
x == 5 | true | Try it »
x == "5" | true | Try it »
=== | equal value and equal type | x === 5 | true | Try it »
x === "5" | false | Try it »
!= | not equal | x != 8 | true | Try it »
!== | not equal value or not equal type | x !== 5 | false | Try it »
x !== "5" | true | Try it »
x !== 8 | true | Try it »
> | greater than | x > 8 | false | Try it »
< | less than | x < 8 | true | Try it »
>= | greater than or equal to | x >= 8 | false | Try it »
<= | less than or equal to | x <= 8 | true


</body>
</html>

**Comment by SigritSiht** [comment]
<html>
<body>


Operator | Description | Comparing | Returns | Try it
-- | -- | -- | -- | --
== | equal to | x == 8 | false | Try it »
x == 5 | true | Try it »
x == "5" | true | Try it »
=== | equal value and equal type | x === 5 | true | Try it »
x === "5" | false | Try it »
!= | not equal | x != 8 | true | Try it »
!== | not equal value or not equal type | x !== 5 | false | Try it »
x !== "5" | true | Try it »
x !== 8 | true | Try it »
> | greater than | x > 8 | false | Try it »
< | less than | x < 8 | true | Try it »
>= | greater than or equal to | x >= 8 | false | Try it »
<= | less than or equal to | x <= 8 | true


</body>
</html>

Just in case I'll paste the current table of comparisons that need to be created as templates

**Comment by turnerrainer** [comment]
@SigritSiht sample services containing the above samples will be part of the AC of this issue, right?

**Comment by turnerrainer** [comment]
Blocked as GUI-part is missing
