### ISSUE TITLE
Service deletion process

### ISSUE THREAD

**Issue by SigritSiht** [buerokratt/Service-Module#24]
AS an Administrative User
I WANT TO have all service related data and models deleted when "delete Service" button is pressed
SO THAT this wouldn't burden the Bürokratt system resources any more

### Acceptance Criteria

> See [comment with link to Rasa-related requirements](https://github.com/buerokratt/Service-Module/issues/24#issuecomment-1471581499)

- [ ] Linked to #41 
- [ ] Can only be applied on inactive services
- [ ] Hard delete

#### GUI

- [ ] Use #11 when deleting a Service
- [ ] Full overview of the consequences of deleting a Service
- [ ] Informational text as `i18n`-based input

##### Buttons

- [ ] `Discard` to send the User back to #11
- [ ] `Delete` triggers the process of actual deletion of a Service

#### DSL

- [ ] #14
- [x] Only inactive Services can be deleted
- [x] Only users in a specified role (defined in Ruuter DSL) can delete a Service by using #40
- [x] Deleting a Service is final (hard delete)

**Comment by turnerrainer** [comment]
Needs input from Veronika Mugra or @KlviG

**Comment by SigritSiht** [comment]
Discussed briefly with BYK team:

1. Delete should mean deletion of everything, incl. intent and its dependencies to other Stories etc.
2. Inactive Services are not deleted from the system but users shoudl be notified that intents will be "inactive" only AFTER training the model.

**Comment by KlviG** [comment]
Rasa-related:
If a Service is deleted:
1) an appropriate .tmp file (service_{NAME}.tmp) is deleted from data/nlu folder
2) an appropriate rule(s) are deleted from data/rules.yml
3) an appropriate story(stories) are deletet from data/stories.yml
4) an appropriate intent name is deleted from domain.yml in "intents:" key.
5) an appropriate response (utter_something) is deleted from domain.yml in "responses:" key

**Comment by turnerrainer** [comment]
[RASA_service_module.docx](https://github.com/buerokratt/Service-Module/files/10988896/RASA_service_module.docx)
