### ISSUE TITLE
Create Ruuter-based SiGa Service Template

### ISSUE THREAD

**Issue by SigritSiht** [buerokratt/Service-Module#26]
AS A {Administrative User / Service Manager / ???}
I WANT TO create template for SiGa
SO THAT SiGa could be used to create services

### Acceptance Criteria

- [ ] Set up [SiGa](https://github.com/open-eid/SiGa) locally for development and mock services
- [ ] Use ID-card, Mobile ID, Smart ID and EU eID _(the latter if possible)_
- [ ] Template can be used for creating service flows #20 
- [ ] SiGa can be integrated with actual SiGa production

#### GUI

- [ ] SiGa drag-and-drop element created in #6 view

#### DSL

- [ ] Ruuter DSL-based SiGa Service template ([see example](https://github.com/buerokratt/Ruuter/blob/main/samples/steps/template.md)) created

#### Endpoints

- [ ] Use `{{ruuter_url}}/jwt/userinfo` as an endpoint to get End Client's current session information

> This endpoint may contain either mock or actual TIM's response, depending on the environment (`play` / `test` vs `prod` accordingly)

**Comment by turnerrainer** [comment]
id.ee/en/article/signing-service-and-digidocservice/
https://github.com/open-eid/SiGa
https://open-eid.github.io/allkirjastamisteenus/

**Comment by Minwasko** [comment]
@turnerrainer currently SiGa template expects an input if you want to sign the document using smartID or mobileID, where does this information come from?
It is missing from the design
![Image](https://github.com/buerokratt/Service-Module/assets/32133759/4d6d1e99-df26-489f-87c5-4905ec2993f9)

I don't know if it could come from TARA, but currently it is missing from the TIM mock data as well.

**Comment by 1AhmedYasser** [comment]
Will Require future developments to modify the Template to add the correct ruuter file uplaoding

Waiting: Ruuter Upload Ability

**Comment by turnerrainer** [comment]
Blocked by https://github.com/buerokratt/NoOps/issues/109

**Comment by ValterAro** [comment]
Given that people need PIN 2 to sign a document then they might not prefer the same choice that they used when they did the authentication nor should the choice be made by the service creator. Therefore the choice between ID-card, Mobile ID and Smart ID should be made by the user. I put the current progress "to groom".

**Comment by rasmusei** [comment]
Needs update
