### ISSUE TITLE
Training/Chat Module: chat history

### ISSUE THREAD

**Issue by SigritSiht** [buerokratt/Service-Module#27]
AS A CSA / Trainer
I WANT TO see a list of finished chats where Services have been applied
SO THAT I could use such chats for learning purposes

### Acceptance Criteria

- [ ] Use Training Module's view for historic chats (http://proto.we.ee/burokratt/treening/ajaloolised-vestlused/ajalugu)
- [ ] Update the Ruuter DSL to fetch a list of finished chats by adding a filter to only fetch the chats where Services have been applied (@turnerrainer )
- [ ] Update GUI to filter out the chats where Services have been applied

**Comment by SigritSiht** [comment]
Is this obsolete because every chat will be visible under History? If not I will add AC's.

**Comment by SigritSiht** [comment]
closed as obsolete
