### ISSUE TITLE
CSA manually triggers a Service on behalf of the End User

### ISSUE THREAD

**Issue by SigritSiht** [buerokratt/Service-Module#28]
AS A Customer Service Agent
I WANT TO have the option to trigger a specific Service from a list of Services for Active conversations
SO THAT if I understand the End User's intent but the bot doesn't, I can trigger the appropriate Service and provide it with appropriate input manually

### Acceptance Criteria

- [ ] list of services added as an element to menu bar
- [ ] agency's or common service can be chosen from the list
- [ ] service can be triggered

Service flow

- [ ] CSA can trigger a Service after taking over the chat
- [ ] The End User is notified about the Service being triggered by the CSA
- [ ] The input is first provided by a CSA (as much as possible) on behalf of the End User
- [ ] The End User sees the input provided by the CSA on behalf of the End User styled differently
- [ ] CSA hands over the chat to the End User to finish providing the Service input (if still needed)

#### GUI

- [ ] On the right side menu, an additional button to trigger a Service appears
- [ ] A button to trigger a Service opens (possibly) a modal with a searchable dropdown to look for a Service to use
- [ ] `i18n` values for `key` values of Rasa service
- [ ] Take #43 into account

#### DSL

- [ ] Use #38

**Comment by SigritSiht** [comment]
[Figma](https://www.figma.com/file/yF3ywx7OaufCTXlQNpJ1ub/B%C3%BCrokratt-Service-module-2023.03?node-id=502-32255&t=EpnGfJHWRBSiJCtv-4).
