### ISSUE TITLE
Create Services by using the Training Module

### ISSUE THREAD

**Issue by SigritSiht** [buerokratt/Service-Module#30]
AS an Administrative User
I WANT TO define not a topic but a service (thus don't want to insert utterance)
SO THAT I CAN create a new Service

### Acceptance Criteria

> https://www.figma.com/file/9Lpy6pdvYaq2M6PxUO6ym4/B%C3%BCrokratt-(Copy)?type=design&node-id=27-1150&mode=design&t=p9feTS3H8vnmRnEB-4

#### Examples of an intent 

- [ ] Every example of an intent can be turned into an intent
- [x] Button "Change to intent" created next to existing buttons _"Muuda" / "Kustuta" ("Edit" / "Delete")_
![image](https://user-images.githubusercontent.com/90505798/220577894-8991f5f1-f148-494e-b52d-48d0f6e493a3.png)

##### Ruuter

The following is combined within 1 Ruuter DSL

- [ ] Use an existing REST service (if exists) to turn an example into an intent -- @turnerrainer 
- [ ] Use an existing REST service (if exists) to delete an example after it was turned into an intent -- @turnerrainer 

#### Intents

- [ ] An additional button "Muuda teenuseks" / "Turn into a Service" is added above examples of a selected intent in addition to the ones shown below
![image](https://user-images.githubusercontent.com/90505798/220581338-61cfb603-5ff8-4a2f-8295-2bd6f50e4a3b.png)
- [ ] Any intent can be turned into a Service
- [ ] Rasa-specific validations when turning an existing story into a Service - _Use [1.2 Change existing intent to service from RASA_service_module.docx](https://github.com/buerokratt/Service-Module/files/10988896/RASA_service_module.docx) by @KlviG as a reference_
- [ ] Only 1 intent can be linked to a specific Service
<s>- [ ] Button will direct to #12</s> _amended 10.01.2024_
<s>- [ ] In GUI, the Service name is pre-filled with the name of the original intent which was converted into a Service</s>_amended 10.01.2024_
- [ ] Intents have different background colours based on being a Service or a Rasa response

**Comment by SigritSiht** [comment]
Discussed this with the BYK team and:
1. Service intent that has not been added to the model, i.e not trained/not part of the model that is currently in use, will also need to be indicated. Probably similarly to "normal" intents where there is a tick next to an intent if it is part of the model.
2. if an intent has been turned into a Service, "Teenus_" needs to be added in front. (This is debatable as we have an AC that makes it possible to understand that intents are different):

- [ ] Intents have different background colours based on being a Service or a Rasa response

3. Utter and a Rasa Story or Rasa Rule must be automatically created. (their actual content will be provided by BYK team).

**Comment by SigritSiht** [comment]
We need to take into consideration the possibility that the user might want to drop everything and not have it as draft.

**Comment by turnerrainer** [comment]
> @turnerrainer [Training Module/GUI/src/services/intents.ts](https://github.com/buerokratt/Training-Module/blob/b18998cdda54ecca799b71db3dcf4f48c8930087/GUI/src/services/intents.ts)
> 
> I think that we are able to use these two:
> 
> * addIntent()
> * deleteExample()

@trevorling there should be Ruuter endpoints you could use. Take a look at [this temporary list of Training Module's endpoints](https://github.com/buerokratt/Buerokratt-onboarding/issues/8) - it's not ideal but it's something until we get our OpenAPI spec done.

**Comment by SigritSiht** [comment]
@turnerrainer I guess you can remove the @turnerrainer's from the task description, as you provided the list of endpoints as a comment?

**Comment by trevorling** [comment]
@SigritSiht @turnerrainer 

Turn intent example into the intent:
There is a check: the intent name must be at least [Training module: /rasa/intents/add]

Please take a look at the examples that are underlined.
Turning these two examples into intent is going to fail.

I hope that I didn't miss something and my understanding is in the same state with the codebase.

(https://github.com/buerokratt/Training-Module/blob/20198cfaad43a6d38114a284eabdb0d44b6af0fa/DSL/Ruuter.private/POST/rasa/intents/add.yml#L22-L26)
![image](https://user-images.githubusercontent.com/53426191/227465394-d1775491-630c-4eff-9d98-42365c6771bd.png)

**Comment by rasmusei** [comment]
Needs DSL grooming

**Comment by ValterAro** [comment]
Short summary: Can not turn an example of an intent into an example as it throws an error.
Pic: 


![Image](https://github.com/buerokratt/Service-Module/assets/122787093/56fb3432-1c34-45f7-911a-cc1309f022e1)

**Comment by ValterAro** [comment]
Short summary: Additionally to the previous error. The intent can not be turned into a service and throws an error.
Pic:


![Image](https://github.com/buerokratt/Service-Module/assets/122787093/e35c6552-8a5e-44ab-9da1-92995bfeb6b5)
