### ISSUE TITLE
Apply different credentials and endpoints of third-party Services based on environment type

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Service-Module#45]
AS A Service Manager
I WANT TO to apply different credentials and endpoints of third-party Services based on the environment type via GUI
SO THAT I could define both test and production endpoints and credentials for the same Service

### Acceptance Criteria

> Based on https://github.com/buerokratt/Service-Module/issues/12#issuecomment-1340724221

- [ ] Services can be created for both `test` and `prod` environments while maintaining the Service as a whole in `prod`
- [ ] The Service Flow is the same regardless of being used in `test` or `prod`
- [ ] `test` and `prod` may, but do not have to have different endpoints
- [ ] If a parameter is missing `test` parameters but has `prod` defined, `prod` parameters are used
- [ ] If a parameter is missing `prod` parameters but has `test` defined, the Service can only be launched in `test`
- [ ] When testing the Service, testing in `test` vs `prod` must be defined and clearly visible

Service states

> `draft`, `inactive`, `active`

- [ ] Service-specific Rasa models can be created for `drafts`
- [ ] Service-specific Rasa models can be created for `inactive`
- [ ] Only Rasa models with all Services can be created for `active`

#### GUI

- [ ] Separate tabs to define API endpoints for `test` and `prod`
- [ ] If the Service is missing `prod` parameters but has them for `test`, this is visually clear in GUI
- [ ] Button `Train Rasa model for the Service`, linked to #20
- [ ] Button `Train Rasa model for all Services`, linked to #20
- [ ] If parameters exist in `prod` but are missing in `test`, `prod` values are used as _placeholders_ in `test`
- [ ] #12 GUI-related AC applied
- [ ] State of Rasa models (untrained, faulty, trained) clearly distinctive in GUI
- [ ] If endpoint-specific credentials file exists, use its `keys` as an input _placeholder_, while not showing their actual `values`

#### DSL

- [ ] Use #88 as a reference, when needed

#### System parameters

> Usernames, passwords, API keys, etc.

- [ ] A separate configuration file for every endpoint
- [ ] Configuration file should only contain sensitive information (username, password, API key)
- [ ] Only `keys` from the configuration file are shown in the GUI
- [ ] Identical structure-wise for `test` and `prod`
- [ ] Based on the chosen environment in use (`test` vs `prod`)

###### Configuration file containing sensitive information

`/config/{env}/nlib_api.yml`
```yaml
API_Nlib:
    nlib_api_key: 12io328382139
    nlib_bot_username: Usr0091
    nlbi_bot_password: pwd9912
```

`/config/{env}/postgres_byk_chat.yml`
```yaml
Postgres_BYK_chat:
    byk_chat_db_uname: iwqudi9wqeu
    byk_chat_db_pwd: 98290213213902
```

###### GUI showing the content from the configuration file

**When working with National Library's API**

API key: `{{API_Nlib.nlib_api_key}}`
Bot username: `{{API_Nlib.nlib_bot_username}}`
Bot paswword: `{{API_Nlib.nlbi_bot_password}}`

**When working with Bürokratt Chat**

API key: `{{API_Nlib.nlib_api_key}}`
Chat DB username: `{{Postgres_BYK_chat.byk_chat_db_uname}}`
Chat DB paswword: `{{Postgres_BYK_chat.byk_chat_db_pwd}}`

**Comment by SigritSiht** [comment]
@turnerrainer is this obsolete? @1AhmedYasser told Mikk and I that it kind of is because we mock everything not send out queries to test envs.
@1AhmedYasser if you want you can provide a more technical explanation here for Rainer.

**Comment by turnerrainer** [comment]
> @turnerrainer is this obsolete? @1AhmedYasser told Mikk and I that it kind of is because we mock everything not send out queries to test envs. @1AhmedYasser if you want you can provide a more technical explanation here for Rainer.

@SigritSiht @1AhmedYasser no, using mock requests does not make them obsolete. This issue does not currently have any AC, I'll add them now.

**Comment by turnerrainer** [comment]
https://rasa.com/docs/rasa/http-api

**Comment by Minwasko** [comment]
@turnerrainer We can't keep secrets/config files with that structure in Ruuter directory, since Ruuter treats it like every other DSL and tries to parse it's logic, which fails since it is not a valid endpoint DSL. 

If we want to keep them in Ruuter we would need to add extra logic to these config files, which doesn't feel right. 
```
assign_secrets:
  assign:
    secrets:
      API_Nlib:
        nlib_api_key: 12io328382139
        nlib_bot_username: Usr0091
        nlbi_bot_password: pwd9912

return_secrets:
  wrapper: false
  return: ${secrets}

```

We could hold these files under `DSL/secrets` next to `DSL/Ruuter` [in this directory](https://github.com/buerokratt/Service-Module/tree/main/DSL), then we don't need any extra info in the config file and structure can stay as it is done in this task example:
```
API_Nlib:
    nlib_api_key: 12io328382139
    nlib_bot_username: Usr0091
    nlbi_bot_password: pwd9912
```

Your call on where should we hold them?
