### ISSUE TITLE
Automatically generating REST endpoint's key fields

### ISSUE THREAD

**Issue by SigritSiht** [buerokratt/Service-Module#9]
AS an Administrative User
I WANT TO get entered API / X-Road request body as pre-filled text fields
SO THAT I CAN have the correct values provided to me automatically

# Acceptance Criteria

- [ ] Get a list of request fields for any given X-Road request
- [ ] Get a list of request fields for any given OpenAPI-compatible REST endpoint
- [ ] Get a list of request fields for any given custom REST endpoint
.....
- [ ] _Provide field type information if possible (mandatory, int/text, etc)_
- [ ] _Take into account types of fields and fields depending on other endpoints_
- [ ] _Re-use responses of previous requests as part of other requests_
.....

#### DSL

- [ ] query triggered
- [ ] values received

#### GUI

> Should be part of other issues, for example by [Service Module Connection Page](https://github.com/buerokratt/Service-Module/issues/12)

- [ ] values printed out on screen
- [ ] error message 1 "Values cannot be queried automatically, please enter them manually" #12 created and triggerable
- [ ] error message 2 "Entered URL is not correct, please check provided information!" created and triggerable
- [ ] unnecessary fields can be deleted
- [ ] mandatory fields cannot be deleted (OpenAPI)

**Comment by turnerrainer** [comment]
@SigritSiht please specify both the user story and AC.

Pre-filled part is a bit confusing - pre-filled with
1. some actual sample data; or
2. extract the structure of the X-road service based on their WSDL showing that this particular service requires personal code to be filled as a mandatory field and an email, first name, and last name as optional ones?

**Comment by 1AhmedYasser** [comment]
@turnerrainer So we would be using x-road and open-api WSDL to get the input parameters for any endpoint ? if so, how do you propose we do it, do we hit a wsdl url and then parse the result or are you thinking of a better approach ?

**Comment by turnerrainer** [comment]
> @turnerrainer So we would be using x-road and open-api WSDL to get the input parameters for any endpoint ? if so, how do you propose we do it, do we hit a wsdl url and then parse the result or are you thinking of a better approach ?

@1AhmedYasser let's start with both one- and multi-level JSONs and cover WSDLs after that.

**Comment by 1AhmedYasser** [comment]
@turnerrainer Got it, so i will be going with the following: services we will support and extract its input parameters and required and optional fields has to based on the OpenAPI specification

For example:

1) PetStore: https://petstore3.swagger.io/api/v3/openapi.json
2) Resql Example: http://localhost:8082/v3/api-docs

**Comment by 1AhmedYasser** [comment]
@turnerrainer We need this feature https://github.com/buerokratt/Ruuter/pull/104 added to Ruuter in-order to pass dynamic url's to DSL's

**Comment by SigritSiht** [comment]
@1AhmedYasser Mikk will most likely need information about what user needs to provide for #12.
